name: Bugi
description: Lisää bugi-ilmoitus. Muista lisätä [Bugi]-riville otsikko ja oikealle projekti-osioon "Tikettien seuranta".
title: "[Bugi] "
labels: [bug]
body:
- type: textarea
  attributes:
    label: Mikä vikana?
    description: Kerro mahdollisimman tarkasti, mikä on vikana. Asiakastietoja ei saa lisätä tikettiin, linkki asiakastietoon riittää.
  validations:
    required: false
- type: textarea
  attributes:
    label: Mitä pitäisi tapahtua
    description: Mitä pitäisi tapahtua?
  validations:
    required: false
- type: textarea
  attributes:
    label: Kuinka toistaa ongelma/asia
    description: Kuinka voi toistaa ongelman/asian?
    placeholder: |
      1. Kohan osio...
      2. Järjestelmäasetus...
      3. Aja '...'
      4. Virheilmoitus...
  validations:
    required: false
- type: textarea
  attributes:
    label: Selain
    description: |
      examples:
        - Firefox versio x.xx
        - Chrome versio x.xx
        - Edge versio x.xx
    render: markdown
  validations:
    required: false
- type: textarea
  attributes:
    label: Jotain muuta?
    description: |
     Lisätietoja aiheesta.
      Vinkki: Voit liittää kuvia tai tiedostoja klikkaamalla tätä aluetta ja vetämällä kuvan tai tiedoston tänne.
  validations:
    required: false
