name: Bugi
description: Lisää tukipyyntö liittyen Kirkes-konversioon
title: "[Bugi] <title>"
labels: [bug]
body:
- type: textarea
  attributes:
    label: Mikä vikana?
    description: Kerro, mikä on vikana.
  validations:
    required: false
- type: textarea
  attributes:
    label: Mitä pitäisi tapahtua
    description: Mitä pitäisi tapahtua?
  validations:
    required: false
- type: textarea
  attributes:
    label: Kuinka toistaa ongelma/asia
    description: Kuinka voi toistaa ongelman/asian?
    placeholder: |
      1. Kohan osio...
      2. Järjestelmäastus...
      3. Aja '...'
      4. Virheilmoitus...
  validations:
    required: false
- type: textarea
  attributes:
    label: Selain
    description: |
      examples:
        - Firefox versio x.xx
        - Chrome
        - Edge
    value: |
        - Firefox:
        - Chrome:
        - Edge:
    render: markdown
  validations:
    required: false
- type: textarea
  attributes:
    label: Jotain muuta?
    description: |
     Lisätietoja aiheesta.
      Vinkki: Voit liittää kuvia tai tiedostoja klikkaamalla tätä aluetta ja vetämällä kuvan tai tiedoston tänne.
  validations:
    required: false
