name: Kehitysehdotus
title: "[Kehitysehdotus]"
labels: ["enhancement"]
description: Lisää kehitysehdotus. Muista lisätä [Kehitysehdotus]-riville otsikko, mutta älä poista jo siinä olevaa tietoa. Lisää oikealle projekti-osioon "Tikettien seuranta".
body:
- type: textarea
  attributes:
    label: Kehitysehdotukseni
    description: Kerro mahdollisimman tarkasti, minkälaista ominaisuutta tai toiminnallisuutta toivot. Asiakastietoja ei saa lisätä tikettiin, linkki asiakastietoon riittää.
  validations:
    required: false
- type: textarea
  attributes:
    label: Jotain muuta?
    description: |
     Lisätietoja aiheesta.
      Vinkki: Voit liittää kuvia tai tiedostoja klikkaamalla tätä aluetta ja vetämällä kuvan tai tiedoston tänne.
  validations:
    required: false
