name: Kehitysehdotus
labels: ["local enhancement"]
projects: ["KohaSuomi/4"]
description: Lisää kehitysehdotus. Muista lisätä tiketin tallennuksen jälkeen tiketille statukseksi "Asiantuntijaryhmään".
body:
- type: textarea
  attributes:
    label: Kehitysehdotukseni
    description: Kerro mahdollisimman tarkasti, minkälaista ominaisuutta tai toiminnallisuutta toivot. Asiakastietoja ei saa lisätä tikettiin, linkki asiakastietoon riittää.
  validations:
    required: false
- type: textarea
  attributes:
    label: Jotain muuta?
    description: |
     Lisätietoja aiheesta.
      Vinkki: Voit liittää kuvia tai tiedostoja klikkaamalla tätä aluetta ja vetämällä kuvan tai tiedoston tänne.
  validations:
    required: false
