name: Kehitysehdotus
labels: ["local enhancement"]
projects: ["KohaSuomi/4"]
description: Lisää kehitysehdotus. Muista lisätä tiketin tallennuksen jälkeen tiketille statukseksi "Asiantuntijaryhmään".
body:
- type: textarea
  attributes:
    label: Kehitysehdotukseni
    description: Kerro mahdollisimman tarkasti, minkälaista ominaisuutta tai toiminnallisuutta toivot. Asiakastietoja ei saa lisätä tikettiin, linkki asiakastietoon riittää.
  validations:
    required: false
- type: textarea
  attributes:
    label: Vaikuttavuus ja kiireellisyys
    description: Miten moneen käyttäjään vaikuttaa, helpottaako työntekoa, minkälainen hyöty muutoksesta on asiakkaille, vaikuttaako tietosuojaan ja datan eheyteen, kuinka kiireellinen asia on, onko taustalla esim. lakimuutos? Lisätietoja aiheesta. Vinkkinä, voit liittää kuvia tai tiedostoja klikkaamalla tätä aluetta ja vetämällä kuvan tai tiedoston tänne.
  validations:
    required: false
