name: Tukipyyntö
description: Lisää tukipyyntö. Muista lisätä tiketille otsikko.
labels: ["help wanted"]
projects: ["KohaSuomi/4"]
body:
- type: textarea
  attributes:
    label: Tukipyyntö
    description: Kerro mahdollisimman tarkasti, mihin tarvitset apua tai mitä pitäisi tehdä. Asiakastietoja ei saa lisätä tikettiin, linkki asiakastietoon riittää.
  validations:
    required: false
- type: textarea
  attributes:
    label: Jotain muuta?
    description: |
     Lisätietoja aiheesta.
      Vinkki: Voit liittää kuvia tai tiedostoja klikkaamalla tätä aluetta ja vetämällä kuvan tai tiedoston tänne.
  validations:
    required: false
